/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

import java.awt.Color; //cores
import java.sql.Connection;
import conexion.ModuloConexao;
import controller.CategoriaController;
import controller.ProdutoController;
import controller.MovimentacaoController;
import java.awt.Component;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import view.TelaCategoria;
import view.TelaMovimentacao;
import view.TelaProduto;
import reports.Relatorios;


/**
 *
 * @author Jhessye Lorrayne
 */
public class TelaInicial extends javax.swing.JFrame {
Connection conexao = null;
    /**
     * Creates new form TelaInicial
     * @throws java.sql.SQLException
     */
    public TelaInicial() throws SQLException {
        initComponents();
        conexao = ModuloConexao.conector(); //inicia a conexao
        carregarResgistrosTela();
        
        this.setLocationRelativeTo(null); // ← Esta linha centraliza o JFrame
        this.setResizable(false); // ← Impede redimensionamento
        this.setTitle("Página Inicial");  // Título personalizado
        
        if (conexao != null){
            System.out.println("CONECTADO");
        }else{
            System.out.println("NÃO CONECTADO");
        }
    }
    
    private void carregarResgistrosTela() throws SQLException{
        
        int totalProduto = ProdutoController.totalRegistrosProduto();
        int totalCategoria = CategoriaController.totalRegistrosCategoria();
        int totalMovimentacao = MovimentacaoController.totalRegistrosMovimentacoes();
        
        textoTotalRegistros.setText("PRODUTOS = " + totalProduto + "\n" +
                            "CATEGORIAS = " + totalCategoria + "\n" +
                            "MOVIMENTAÇÕES = " + totalMovimentacao);
        textoTotalRegistros.setEditable(false);
        textoTotalRegistros.setOpaque(false); // transparente
        textoTotalRegistros.setAlignmentX(Component.CENTER_ALIGNMENT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        bntRelatorio = new javax.swing.JButton();
        bntCategoria = new javax.swing.JButton();
        bntProduto = new javax.swing.JButton();
        bntMovimentacao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        criado = new javax.swing.JLabel();
        professores = new javax.swing.JLabel();
        disciplinas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textoTotalRegistros = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(100, 100));

        bntRelatorio.setBackground(new java.awt.Color(0, 0, 0));
        bntRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        bntRelatorio.setText("RELATÓRIOS");
        bntRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntRelatorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntRelatorioMouseExited(evt);
            }
        });
        bntRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRelatorioActionPerformed(evt);
            }
        });

        bntCategoria.setBackground(new java.awt.Color(0, 0, 0));
        bntCategoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntCategoria.setForeground(new java.awt.Color(255, 255, 255));
        bntCategoria.setText("CATEGORIA");
        bntCategoria.setToolTipText("");
        bntCategoria.setBorder(null);
        bntCategoria.setBorderPainted(false);
        bntCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bntCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntCategoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntCategoriaMouseExited(evt);
            }
        });
        bntCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCategoriaActionPerformed(evt);
            }
        });

        bntProduto.setBackground(new java.awt.Color(0, 0, 0));
        bntProduto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntProduto.setForeground(new java.awt.Color(255, 255, 255));
        bntProduto.setText("PRODUTOS");
        bntProduto.setBorder(null);
        bntProduto.setBorderPainted(false);
        bntProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntProdutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntProdutoMouseExited(evt);
            }
        });
        bntProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntProdutoActionPerformed(evt);
            }
        });

        bntMovimentacao.setBackground(new java.awt.Color(0, 0, 0));
        bntMovimentacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntMovimentacao.setForeground(new java.awt.Color(255, 255, 255));
        bntMovimentacao.setText("MOVIMENTAÇÕES");
        bntMovimentacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntMovimentacaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntMovimentacaoMouseExited(evt);
            }
        });
        bntMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMovimentacaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Sistema de Estoque");

        criado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        criado.setForeground(new java.awt.Color(0, 0, 0));
        criado.setText("Criado por: Jhessye Lorrayne Fraga da Silva");

        professores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        professores.setForeground(new java.awt.Color(0, 0, 0));
        professores.setText("Professores: Howard Roatti, Cinthia Cristina L. Caliari");

        disciplinas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        disciplinas.setForeground(new java.awt.Color(0, 0, 0));
        disciplinas.setText("Disciplinas: Banco de Dados, Linguagem de Programação O.O. ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("TOTAL DE REGISTROS EXISTENTES");

        textoTotalRegistros.setColumns(20);
        textoTotalRegistros.setRows(5);
        textoTotalRegistros.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(bntCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(professores)
                            .addComponent(criado)
                            .addComponent(disciplinas))))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(314, 314, 314))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoTotalRegistros))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(criado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disciplinas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(professores)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRelatorioActionPerformed
        // TODO add your handling code here:
        Relatorios telaRelatorio = new Relatorios();
        
        telaRelatorio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntRelatorioActionPerformed

    private void bntCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCategoriaActionPerformed
        // TODO add your handling code here:
        TelaCategoria telaCategoria = new TelaCategoria();
        
        telaCategoria.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntCategoriaActionPerformed

    private void bntProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntProdutoActionPerformed
        // TODO add your handling code here:
        TelaProduto telaProduto = new TelaProduto();
        
        telaProduto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntProdutoActionPerformed

    private void bntMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMovimentacaoActionPerformed
        // TODO add your handling code here:
        TelaMovimentacao telaMovimentacao = new TelaMovimentacao();
        
        telaMovimentacao.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntMovimentacaoActionPerformed

    private void bntCategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCategoriaMouseEntered
        // TODO add your handling code here:
        bntCategoria.setBackground(Color.LIGHT_GRAY); // muda a cor quando o mouse passa por cima
        bntCategoria.setForeground(Color.BLACK);
    }//GEN-LAST:event_bntCategoriaMouseEntered

    private void bntCategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCategoriaMouseExited
        // TODO add your handling code here:
        bntCategoria.setBackground(Color.BLACK);
        bntCategoria.setForeground(Color.WHITE);
    }//GEN-LAST:event_bntCategoriaMouseExited

    private void bntProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntProdutoMouseEntered
        // TODO add your handling code here:
        bntProduto.setBackground(Color.LIGHT_GRAY); // muda a cor quando o mouse passa por cima
        bntProduto.setForeground(Color.BLACK);
    }//GEN-LAST:event_bntProdutoMouseEntered

    private void bntProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntProdutoMouseExited
        // TODO add your handling code here:
        bntProduto.setBackground(Color.BLACK);
        bntProduto.setForeground(Color.WHITE);
    }//GEN-LAST:event_bntProdutoMouseExited

    private void bntRelatorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntRelatorioMouseEntered
        // TODO add your handling code here:
        bntRelatorio.setBackground(Color.LIGHT_GRAY); // muda a cor quando o mouse passa por cima
        bntRelatorio.setForeground(Color.BLACK);
    }//GEN-LAST:event_bntRelatorioMouseEntered

    private void bntRelatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntRelatorioMouseExited
        // TODO add your handling code here:
        bntRelatorio.setBackground(Color.BLACK);
        bntRelatorio.setForeground(Color.WHITE);
    }//GEN-LAST:event_bntRelatorioMouseExited

    private void bntMovimentacaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntMovimentacaoMouseEntered
        // TODO add your handling code here:
        bntMovimentacao.setBackground(Color.LIGHT_GRAY); // muda a cor quando o mouse passa por cima
        bntMovimentacao.setForeground(Color.BLACK);
    }//GEN-LAST:event_bntMovimentacaoMouseEntered

    private void bntMovimentacaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntMovimentacaoMouseExited
        // TODO add your handling code here:
        bntMovimentacao.setBackground(Color.BLACK);
        bntMovimentacao.setForeground(Color.WHITE);
    }//GEN-LAST:event_bntMovimentacaoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new TelaInicial().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCategoria;
    private javax.swing.JButton bntMovimentacao;
    private javax.swing.JButton bntProduto;
    private javax.swing.JButton bntRelatorio;
    private javax.swing.JLabel criado;
    private javax.swing.JLabel disciplinas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel professores;
    private javax.swing.JTextArea textoTotalRegistros;
    // End of variables declaration//GEN-END:variables
}
