/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import principal.TelaInicial;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import controller.ProdutoController;
import javax.swing.JOptionPane;
import controller.MovimentacaoController;
import model.Movimentacao;
import model.Produto;

/**
 *
 * @author Jhessye Lorrayne
 */
public class ExcluirProduto extends javax.swing.JFrame {

    /**
     * Creates new form AlterarProduto
     */
    public ExcluirProduto() {
        initComponents();
        preencherListaProduto();
        
        this.setLocationRelativeTo(null); // ← Esta linha centraliza o JFrame
        this.setResizable(false); // ← Impede redimensionamento
        this.setTitle("Excluir Produto");  // Título personalizado
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bntVoltarExcluirProduto = new javax.swing.JButton();
        listaProduto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        bntOkExcluirProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("EXCLUIR PRODUTO");

        bntVoltarExcluirProduto.setBackground(new java.awt.Color(0, 0, 0));
        bntVoltarExcluirProduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntVoltarExcluirProduto.setForeground(new java.awt.Color(255, 255, 255));
        bntVoltarExcluirProduto.setText("VOLTAR");
        bntVoltarExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarExcluirProdutoActionPerformed(evt);
            }
        });

        listaProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaProdutoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Selecione o produto");

        bntOkExcluirProduto.setBackground(new java.awt.Color(0, 0, 0));
        bntOkExcluirProduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntOkExcluirProduto.setForeground(new java.awt.Color(255, 255, 255));
        bntOkExcluirProduto.setText("OK");
        bntOkExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntOkExcluirProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntVoltarExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(bntOkExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(listaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(bntOkExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(bntVoltarExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntVoltarExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarExcluirProdutoActionPerformed
        // TODO add your handling code here:
        TelaInicial telaInicial = null;
        try {
            telaInicial = new TelaInicial();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProduto.class.getName()).log(Level.SEVERE, null, ex);
        }

        telaInicial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntVoltarExcluirProdutoActionPerformed

    private void bntOkExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntOkExcluirProdutoActionPerformed
        try {
            boolean excluir = true;
            
            Produto p = new Produto();
            p = excluir(); //pega o produto que a pessoa selecionou
            
            if (p == null ) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
            }
            
            //se tiver movimentações com o produto, excluir primeiro as movimentações do produto
            for (Movimentacao m : MovimentacaoController.mostrarMovimentacoes("Lista")){
                
                if (p.getNome().equals(m.getProduto().getNome())){
                    excluir = false;
                }
                
            }
            
            if (excluir){
                ProdutoController.excluirProduto(p);
                //pergunta se quer continuar
                int resposta = JOptionPane.showConfirmDialog(
                    null, 
                    "Produto excluido com sucesso!\nDeseja excluir outro produto?",
                    "Continuar?",
                    JOptionPane.YES_NO_OPTION
                );

                if (resposta == JOptionPane.YES_OPTION) {
                    preencherListaProduto();
                } else {
                    TelaInicial telaInicial = new TelaInicial();
                    
                    this.setVisible(false);
                    telaInicial.setVisible(true);
                }
            }else{
                JOptionPane.showMessageDialog(null, "O produto selecionado tem movimentações agregadas\nExclua as movimentações deste produto PRIMEIRO. ");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ExcluirProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bntOkExcluirProdutoActionPerformed

    
    public Produto excluir() throws SQLException{
        Produto p = new Produto();
        
        p = ProdutoController.mostrarPordutos("Lista").get(listaProduto.getSelectedIndex());
          
        return p;
    }
    
    
    private void preencherListaProduto(){
        try {
            listaProduto.removeAllItems();
            // Adiciona todas as categorias do ArrayList no JComboBox
            for (Produto produto : ProdutoController.mostrarPordutos("Lista")) {
                listaProduto.addItem(produto.getIdProduto() +" | "+ produto.getNome()+" | "+produto.getDescricao()+" | "+produto.getMarca()+" | "+produto.getPreco());
            }
        } catch (SQLException ex) {
            Logger.getLogger(InserirProduto.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao carregar produtos: " + ex.getMessage());
        }
    }
    
    private void listaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntOkExcluirProduto;
    private javax.swing.JButton bntVoltarExcluirProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> listaProduto;
    // End of variables declaration//GEN-END:variables
}
