/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import principal.TelaInicial;
import model.Produto;
import model.Categoria;
import controller.CategoriaController;
import controller.ProdutoController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Jhessye Lorrayne
 */
public class InserirProduto extends javax.swing.JFrame {

    /**
     * Creates new form InserirProduto
     * @throws java.sql.SQLException
     */
    public InserirProduto() throws SQLException {
        initComponents();
        carregarListaCategorias();
        
        this.setLocationRelativeTo(null); // ← Esta linha centraliza o JFrame
        this.setResizable(false); // ← Impede redimensionamento
        this.setTitle("Cadastrar Produto");  // Título personalizado
    }
    
    public void carregarListaCategorias(){
        try {
            listaCategoriaP.removeAllItems();
            // Adiciona todas as categorias do ArrayList no JComboBox
            for (Categoria categoria : CategoriaController.mostrarCategorias("Lista")) {
                listaCategoriaP.addItem(categoria.getNome());
            }
        } catch (SQLException ex) {
            Logger.getLogger(InserirProduto.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao carregar categorias: " + ex.getMessage());
        }
    }
    
    public boolean cadastrarProduto() throws SQLException{
        
        String nome = textNomeP.getText().trim();
        String descricao = textDescricaoP.getText().trim();
        String marca = textMarcaP.getText().trim();
        String preco = textPrecoP.getText().trim();
        Categoria categoriaP = new Categoria();
        
        for (int i = 0; i<= listaCategoriaP.getSelectedIndex(); i++){
            if(i == listaCategoriaP.getSelectedIndex()){
                categoriaP = CategoriaController.mostrarCategorias("Lista").get(i);
            }
        }
        
        if (nome.isEmpty() || descricao.isEmpty() || marca.isEmpty() || preco.isEmpty() || categoriaP == null ) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        return false;
        }
        
        try {
            double precoP = Double.parseDouble(preco); //tranforma pra numerico

            //n pode ser negativo
            if (precoP <= 0) {
                JOptionPane.showMessageDialog(null, "O preço deve ser maior que zero!");
                return false;
            }

            Produto produto = new Produto(nome, descricao, marca, precoP, categoriaP.getIdCategoria()); //cria o produto
            return ProdutoController.inserirProduto(produto);//insere

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite um preço válido! Use ponto para decimais.");
            return false;
        }
    
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bntVoltarP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textNomeP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDescricaoP = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        textMarcaP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textPrecoP = new javax.swing.JTextField();
        bntOkP = new javax.swing.JButton();
        listaCategoriaP = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CADASTRAR PRODUTO");

        bntVoltarP.setBackground(new java.awt.Color(0, 0, 0));
        bntVoltarP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntVoltarP.setForeground(new java.awt.Color(255, 255, 255));
        bntVoltarP.setText("VOLTAR");
        bntVoltarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarPActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome");

        textNomeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomePActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Descrição");

        textDescricaoP.setColumns(20);
        textDescricaoP.setRows(5);
        jScrollPane1.setViewportView(textDescricaoP);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Marca");

        textMarcaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMarcaPActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Categoria");

        textPrecoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrecoPActionPerformed(evt);
            }
        });

        bntOkP.setBackground(new java.awt.Color(0, 0, 0));
        bntOkP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntOkP.setForeground(new java.awt.Color(255, 255, 255));
        bntOkP.setText("OK");
        bntOkP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntOkPActionPerformed(evt);
            }
        });

        listaCategoriaP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaCategoriaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaCategoriaPActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Preço");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel1)
                .addContainerGap(358, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPrecoP, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(listaCategoriaP, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(textNomeP)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(jLabel6)
                            .addComponent(textMarcaP, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bntOkP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229)))
                .addComponent(bntVoltarP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bntVoltarP, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaCategoriaP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textMarcaP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textPrecoP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(bntOkP, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntVoltarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarPActionPerformed
        // TODO add your handling code here:
        TelaInicial telaInicial = null;
        try {
            telaInicial = new TelaInicial();
        } catch (SQLException ex) {
            Logger.getLogger(InserirProduto.class.getName()).log(Level.SEVERE, null, ex);
        }

        telaInicial.setVisible(true);
        limparCampos();
        this.setVisible(false);
    }//GEN-LAST:event_bntVoltarPActionPerformed

    private void textNomePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomePActionPerformed

    private void textMarcaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMarcaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMarcaPActionPerformed

    private void textPrecoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrecoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrecoPActionPerformed

    private void bntOkPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntOkPActionPerformed
        try {
            // TODO add your handling code here:
            boolean cadastro = cadastrarProduto();
            
            if (cadastro){
                //pergunta se quer continuar
                int resposta = JOptionPane.showConfirmDialog(
                    null, 
                    "Produto cadastrado com sucesso!\nDeseja cadastrar outro produto?",
                    "Continuar?",
                    JOptionPane.YES_NO_OPTION
                );

                if (resposta == JOptionPane.YES_OPTION) {
                    limparCampos(); //limpar os campos
                } else {
                    TelaInicial telaInicial = new TelaInicial();
                    
                    limparCampos(); //limpar os campos
                    this.setVisible(false);
                    telaInicial.setVisible(true);
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(InserirProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bntOkPActionPerformed

    private void listaCategoriaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaCategoriaPActionPerformed
      
    }//GEN-LAST:event_listaCategoriaPActionPerformed

    private void limparCampos() {
        textNomeP.setText("");
        textDescricaoP.setText("");
        textMarcaP.setText("");
        textPrecoP.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new InserirProduto().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(InserirProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntOkP;
    private javax.swing.JButton bntVoltarP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> listaCategoriaP;
    private javax.swing.JTextArea textDescricaoP;
    private javax.swing.JTextField textMarcaP;
    private javax.swing.JTextField textNomeP;
    private javax.swing.JTextField textPrecoP;
    // End of variables declaration//GEN-END:variables
}
