/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import principal.TelaInicial;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jhessye Lorrayne
 */
public class TelaMovimentacao extends javax.swing.JFrame {

    /**
     * Creates new form Movimentacao
     */
    public TelaMovimentacao() {
        initComponents();
        this.setLocationRelativeTo(null); // ← Esta linha centraliza o JFrame
        this.setResizable(false); // ← Impede redimensionamento
        this.setTitle("Movimentações");  // Título personalizado
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntVoltarM = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bntInserirM = new javax.swing.JButton();
        bntAlterarM = new javax.swing.JButton();
        bntExcluirM = new javax.swing.JButton();
        bntVerM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bntVoltarM.setBackground(new java.awt.Color(0, 0, 0));
        bntVoltarM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntVoltarM.setForeground(new java.awt.Color(255, 255, 255));
        bntVoltarM.setText("VOLTAR");
        bntVoltarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarMActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("MOVIMENTAÇÕES");

        bntInserirM.setBackground(new java.awt.Color(0, 0, 0));
        bntInserirM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntInserirM.setForeground(new java.awt.Color(255, 255, 255));
        bntInserirM.setText("INSERIR");
        bntInserirM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntInserirMActionPerformed(evt);
            }
        });

        bntAlterarM.setBackground(new java.awt.Color(0, 0, 0));
        bntAlterarM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntAlterarM.setForeground(new java.awt.Color(255, 255, 255));
        bntAlterarM.setText("ALTERAR");
        bntAlterarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAlterarMActionPerformed(evt);
            }
        });

        bntExcluirM.setBackground(new java.awt.Color(0, 0, 0));
        bntExcluirM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntExcluirM.setForeground(new java.awt.Color(255, 255, 255));
        bntExcluirM.setText("EXCLUIR");
        bntExcluirM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirMActionPerformed(evt);
            }
        });

        bntVerM.setBackground(new java.awt.Color(0, 0, 0));
        bntVerM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntVerM.setForeground(new java.awt.Color(255, 255, 255));
        bntVerM.setText("VER");
        bntVerM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVerMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bntVoltarM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bntExcluirM, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163)
                                .addComponent(bntVerM, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bntInserirM, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntAlterarM, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(226, 226, 226))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(367, 367, 367))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntInserirM, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntAlterarM, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntExcluirM, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntVerM, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(bntVoltarM, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntVoltarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarMActionPerformed
        // TODO add your handling code here:
        TelaInicial telaInicial = null;
        try {
            telaInicial = new TelaInicial();
        } catch (SQLException ex) {
            Logger.getLogger(TelaMovimentacao.class.getName()).log(Level.SEVERE, null, ex);
        }

        telaInicial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntVoltarMActionPerformed

    private void bntVerMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVerMActionPerformed
        // TODO add your handling code here:
        VerMovimentacao telaVerMovimentacao = new VerMovimentacao();
        
        telaVerMovimentacao.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntVerMActionPerformed

    private void bntInserirMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntInserirMActionPerformed
        // TODO add your handling code here:
        InserirMovimentacao telaInserirMovimentacao = new InserirMovimentacao();
        
        telaInserirMovimentacao.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntInserirMActionPerformed

    private void bntExcluirMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirMActionPerformed
        // TODO add your handling code here:
        ExcluirMovimentacao telaExcluirMovimentacao = new ExcluirMovimentacao();
        
        telaExcluirMovimentacao.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntExcluirMActionPerformed

    private void bntAlterarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAlterarMActionPerformed
        // TODO add your handling code here:
        AtualizarMovimentacao telaAtualizarMovimentacao = new AtualizarMovimentacao();
        
        telaAtualizarMovimentacao.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntAlterarMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaMovimentacao().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAlterarM;
    private javax.swing.JButton bntExcluirM;
    private javax.swing.JButton bntInserirM;
    private javax.swing.JButton bntVerM;
    private javax.swing.JButton bntVoltarM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
