/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.excluir.ExcluirCategoria;
import view.atualizar.AtualizarCategoria;
import principal.TelaInicial;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jhessye Lorrayne
 */
public class TelaCategoria extends javax.swing.JFrame {

    /**
     * Creates new form Categoria
     */
    public TelaCategoria() {
        initComponents();
        
        this.setLocationRelativeTo(null); // ← Esta linha centraliza o JFrame
        this.setResizable(false); // ← Impede redimensionamento
        this.setTitle("Categorias");  // Título personalizado
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntVoltarC = new javax.swing.JButton();
        bntInserirC = new javax.swing.JButton();
        bntExcluirC = new javax.swing.JButton();
        bntVerC = new javax.swing.JButton();
        bntAlterarC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bntVoltarC.setBackground(new java.awt.Color(0, 0, 0));
        bntVoltarC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntVoltarC.setForeground(new java.awt.Color(255, 255, 255));
        bntVoltarC.setText("VOLTAR");
        bntVoltarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarCActionPerformed(evt);
            }
        });

        bntInserirC.setBackground(new java.awt.Color(0, 0, 0));
        bntInserirC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntInserirC.setForeground(new java.awt.Color(255, 255, 255));
        bntInserirC.setText("INSERIR");
        bntInserirC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntInserirCActionPerformed(evt);
            }
        });

        bntExcluirC.setBackground(new java.awt.Color(0, 0, 0));
        bntExcluirC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntExcluirC.setForeground(new java.awt.Color(255, 255, 255));
        bntExcluirC.setText("EXCLUIR");
        bntExcluirC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirCActionPerformed(evt);
            }
        });

        bntVerC.setBackground(new java.awt.Color(0, 0, 0));
        bntVerC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntVerC.setForeground(new java.awt.Color(255, 255, 255));
        bntVerC.setText("VER");
        bntVerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVerCActionPerformed(evt);
            }
        });

        bntAlterarC.setBackground(new java.awt.Color(0, 0, 0));
        bntAlterarC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntAlterarC.setForeground(new java.awt.Color(255, 255, 255));
        bntAlterarC.setText("ALTERAR");
        bntAlterarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAlterarCActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CATEGORIA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bntVoltarC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bntExcluirC, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163)
                                .addComponent(bntVerC, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bntInserirC, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntAlterarC, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(406, 406, 406))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntInserirC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntAlterarC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntExcluirC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntVerC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(bntVoltarC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntVoltarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarCActionPerformed
        // TODO add your handling code here:
        TelaInicial telaInicial = null;
        try {
            telaInicial = new TelaInicial();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCategoria.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        telaInicial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntVoltarCActionPerformed

    private void bntVerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVerCActionPerformed
        // TODO add your handling code here:
        VerCategoria telaVerCategoria = null;
        try {
            telaVerCategoria = new VerCategoria();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCategoria.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        telaVerCategoria.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntVerCActionPerformed

    private void bntInserirCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntInserirCActionPerformed
        // TODO add your handling code here:
        InserirCategoria telaInserirCategoria = new InserirCategoria();
        
        telaInserirCategoria.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntInserirCActionPerformed

    private void bntExcluirCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirCActionPerformed
        // TODO add your handling code here:
        ExcluirCategoria telaExcluirCategoria = new ExcluirCategoria();
        
        telaExcluirCategoria.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntExcluirCActionPerformed

    private void bntAlterarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAlterarCActionPerformed
        // TODO add your handling code here:
        AtualizarCategoria telaAtualizarCategoria = new AtualizarCategoria();
        
        telaAtualizarCategoria.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntAlterarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaCategoria().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAlterarC;
    private javax.swing.JButton bntExcluirC;
    private javax.swing.JButton bntInserirC;
    private javax.swing.JButton bntVerC;
    private javax.swing.JButton bntVoltarC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
