/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Produto;
/**
 *
 * @author Jhessye Lorrayne
 */
public class TelaProduto extends javax.swing.JFrame {

    /**
     * Creates new form Produto
     */
    public TelaProduto() {
        initComponents();
        this.setLocationRelativeTo(null); // ← Esta linha centraliza o JFrame
        this.setResizable(false); // ← Impede redimensionamento
        this.setTitle("Produtos");  // Título personalizado
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntVoltarP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bntInserirP = new javax.swing.JButton();
        bntAlterarP = new javax.swing.JButton();
        bntExcluirP = new javax.swing.JButton();
        bntVerP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bntVoltarP.setBackground(new java.awt.Color(0, 0, 0));
        bntVoltarP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntVoltarP.setForeground(new java.awt.Color(255, 255, 255));
        bntVoltarP.setText("VOLTAR");
        bntVoltarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarPActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PRODUTOS");

        bntInserirP.setBackground(new java.awt.Color(0, 0, 0));
        bntInserirP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntInserirP.setForeground(new java.awt.Color(255, 255, 255));
        bntInserirP.setText("INSERIR");
        bntInserirP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntInserirPActionPerformed(evt);
            }
        });

        bntAlterarP.setBackground(new java.awt.Color(0, 0, 0));
        bntAlterarP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntAlterarP.setForeground(new java.awt.Color(255, 255, 255));
        bntAlterarP.setText("ALTERAR");

        bntExcluirP.setBackground(new java.awt.Color(0, 0, 0));
        bntExcluirP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntExcluirP.setForeground(new java.awt.Color(255, 255, 255));
        bntExcluirP.setText("EXCLUIR");
        bntExcluirP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirPActionPerformed(evt);
            }
        });

        bntVerP.setBackground(new java.awt.Color(0, 0, 0));
        bntVerP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntVerP.setForeground(new java.awt.Color(255, 255, 255));
        bntVerP.setText("VER");
        bntVerP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVerPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bntVoltarP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(bntExcluirP, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(163, 163, 163)
                                    .addComponent(bntVerP, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(bntInserirP, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bntAlterarP, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(178, 178, 178)))
                        .addGap(234, 234, 234))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntInserirP, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntAlterarP, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntExcluirP, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntVerP, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(bntVoltarP, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntVoltarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarPActionPerformed
        // TODO add your handling code here:
        TelaInicial telaInicial = null;
        try {
            telaInicial = new TelaInicial();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProduto.class.getName()).log(Level.SEVERE, null, ex);
        }

        telaInicial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntVoltarPActionPerformed

    private void bntVerPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVerPActionPerformed
        // TODO add your handling code here:
        VerProduto telaVerProdutoDB = null;
        try {
            telaVerProdutoDB = new VerProduto();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProduto.class.getName()).log(Level.SEVERE, null, ex);
        }

        telaVerProdutoDB.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntVerPActionPerformed

    private void bntInserirPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntInserirPActionPerformed
        // TODO add your handling code here:
        
        InserirProduto telaInserirProduto = null;
        try {
            telaInserirProduto = new InserirProduto();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        telaInserirProduto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntInserirPActionPerformed

    private void bntExcluirPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirPActionPerformed
        // TODO add your handling code here:
        ExcluirProduto telaExcluirProduto = null;
        telaExcluirProduto = new ExcluirProduto();
        
        telaExcluirProduto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntExcluirPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaProduto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAlterarP;
    private javax.swing.JButton bntExcluirP;
    private javax.swing.JButton bntInserirP;
    private javax.swing.JButton bntVerP;
    private javax.swing.JButton bntVoltarP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
