/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.excluir;

import controller.MovimentacaoController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Movimentacao;
import principal.TelaInicial;
import view.InserirCategoria;

/**
 *
 * @author Jhessye Lorrayne
 */
public class ExcluirMovimentacao extends javax.swing.JFrame {

    /**
     * Creates new form ExcluirMovimentacao
     */
    public ExcluirMovimentacao() {
        initComponents();
        carregarMovimentacoes();
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Excluir Movimentacoes");
    }
    
    public void carregarMovimentacoes(){
        try {
            listaExcluirCategoriaM.removeAllItems();
            for (Movimentacao movimentacao : MovimentacaoController.mostrarMovimentacoes("Lista")) {
                listaExcluirCategoriaM.addItem(String.valueOf(movimentacao.getIdMovimentacao()+" | "+movimentacao.getData()+" | "+movimentacao.getProduto().getNome()));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ExcluirMovimentacao.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao carregar movimentações: " + ex.getMessage());
        }
    }
    
    public Movimentacao excluir() throws SQLException{
        int idx = listaExcluirCategoriaM.getSelectedIndex();
        if (idx < 0) return null;
        return MovimentacaoController.mostrarMovimentacoes("Lista").get(idx);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listaExcluirCategoriaM = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        bntVoltarExcluirMovimentacao = new javax.swing.JButton();
        btnOkExcluirMovimentacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("EXCLUIR MOVIMENTAÇÃO");

        listaExcluirCategoriaM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaExcluirCategoriaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaExcluirCategoriaMActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Movimentação");

        bntVoltarExcluirMovimentacao.setBackground(new java.awt.Color(0, 0, 0));
        bntVoltarExcluirMovimentacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntVoltarExcluirMovimentacao.setForeground(new java.awt.Color(255, 255, 255));
        bntVoltarExcluirMovimentacao.setText("VOLTAR");
        bntVoltarExcluirMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarExcluirMovimentacaoActionPerformed(evt);
            }
        });

        btnOkExcluirMovimentacao.setBackground(new java.awt.Color(0, 0, 0));
        btnOkExcluirMovimentacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOkExcluirMovimentacao.setForeground(new java.awt.Color(255, 255, 255));
        btnOkExcluirMovimentacao.setText("OK");
        btnOkExcluirMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkExcluirMovimentacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listaExcluirCategoriaM, javax.swing.GroupLayout.Alignment.LEADING, 0, 589, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 498, Short.MAX_VALUE)))
                .addGap(191, 191, 191))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(831, Short.MAX_VALUE)
                .addComponent(bntVoltarExcluirMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(btnOkExcluirMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaExcluirCategoriaM, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnOkExcluirMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(bntVoltarExcluirMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaExcluirCategoriaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaExcluirCategoriaMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaExcluirCategoriaMActionPerformed

    private void bntVoltarExcluirMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarExcluirMovimentacaoActionPerformed
        TelaInicial telaInicial = null;
        
        try {
            telaInicial = new TelaInicial();
        } catch (SQLException ex) {
            Logger.getLogger(InserirCategoria.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        telaInicial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntVoltarExcluirMovimentacaoActionPerformed

    private void btnOkExcluirMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkExcluirMovimentacaoActionPerformed
        try {
            Movimentacao m = excluir();

            if (m == null) {
                JOptionPane.showMessageDialog(null, "Selecione uma movimentação.");
                return;
            }

            if (MovimentacaoController.excluirMovimentacao(m)) {
                int resposta = JOptionPane.showConfirmDialog(
                    null,
                    "Movimentação excluída com sucesso!\nDeseja excluir outra movimentação?",
                    "Continuar?",
                    JOptionPane.YES_NO_OPTION
                );
                if (resposta == JOptionPane.YES_OPTION) {
                    carregarMovimentacoes();
                } else {
                    TelaInicial telaInicial = new TelaInicial();
                    this.setVisible(false);
                    telaInicial.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possível excluir a movimentação.");
            }

        } catch (SQLException ex) {
            Logger.getLogger(ExcluirMovimentacao.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao processar exclusão: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnOkExcluirMovimentacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirMovimentacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntVoltarExcluirMovimentacao;
    private javax.swing.JButton btnOkExcluirMovimentacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> listaExcluirCategoriaM;
    // End of variables declaration//GEN-END:variables
}
